contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path('contact/', views.DefaultContactView.as_view(), name='DefaultContactView'),
]

movie/urls.py
from django.urls import path
from .import views
from .models import *

app_name = 'movie'
urlpatterns = [
    path('', views.MoviesView.as_view(), name='movies_list'),
    path('subscribe/', views.email_sender, name='email_sender'),
    path('<str:movie_slug>', views.MovieDetailView.as_view(), name='movie_detail'),
    path('add_comment/<int:movie_id>/', views.AddComment.as_view(), name='addcomment_view'),
    path('movies_list/', views.List.as_view(), name='list'),
    path('actor/<str:slug>/', views.ActorView.as_view(), name='actor_detail'),
    path('results/', views.FilterMoviesView.as_view(), name='search_result'),
    path('likes/', views.like_movie, name='likes'),
    path('news/', views.News.as_view(), name='news'),
    path('news/<str:slug>/', views.NewsView.as_view(model=News), name='news_detail'),
    path('category/<str:category_slug>/', views.CategoryMoviesView.as_view(), name='category_view'),
   

]
handler404 = 'movie.views.handler404'

onemovie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie.urls', namespace='movie')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),


]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,  document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

contact/models.py
from django.db import models

# Create your models here.

class Contact(models.Model):
    email = models.EmailField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

    def get_absolute_url(self):
        pass


class DefaultContact(models.Model):
    first_name = models.CharField('First name', max_length=100)
    last_name = models.CharField('Last name', max_length=100)
    subject = models.CharField('Subject', max_length=100)
    email = models.EmailField('Email', max_length=100)
    message = models.TextField('Message')

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'Default Contact'
        verbose_name_plural = 'Default Contacts'

contact/forms.py
from .models import Contact, DefaultContact
from django import forms
from django.forms import Textarea

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('email',)

class DefaultContactForm(forms.ModelForm):
    class Meta:
        model = DefaultContact
        fields = ('first_name', 'last_name', 'subject', 'email', 'message',)
        widgets = {
            'message': Textarea(attrs={"autocomplete":"off", 'cols':30, 'rows':8}),
        }

contact/views.py
from django.views.generic.base import View
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import DefaultContact
from .forms import DefaultContactForm
from .service import send

class DefaultContactView(View):
    def get(self, request):
        return render(request, 'contact.html')

    def post(self, request):
        if request.method == 'POST':
            form = DefaultContactForm(request.POST)
            if form.is_valid():
                print(form)
                form.save()
                last_user = DefaultContact.objects.all().order_by('id')[:1]
                for email in last_user:
                    if email:
                        send(email)
        else:
            form = DefaultContactForm()

        return render(request, 'contact.html', {'default_form':form})

templates/actor_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- single -->
<div class="single-page-agile-main">
<div class="container">
		<!-- /w3l-medile-movies-grids -->
			<div class="agileits-single-top">
				<ol class="breadcrumb">
				  <li><a href="{% url 'movie:movies_list' %}">Bosh sahifa</a></li>
				  <li class="active">{{ actor.name.upper }}  haqida</li>
				</ol>
			</div>
			<div class="single-page-agile-info">
                   <!-- /movie-browse-agile -->
                <div class="show-top-grids-w3lagile">
				<div class="col-sm-8 single-left">
					<div class="song">
						<div class="song-info">
							<h3>{{ actor.name.upper }}</h3>
					</div>
						<div class="video-grid-single-page-agileits" style="width: 75%; height: auto;">
							<div data-video="dLmKio67pVQ" id="video">
							<img src="{{actor.image.url}}" alt="" class="img-responsive" /> </div>
						</div>
					</div>

					<div class="clearfix"> </div>
					<!-- <h3>Actors</h3>
					<div class="w3_agile_banner_bottom_grid">
						<div id="owl-demo" class="owl-carousel owl-theme">
							{% for actor in movie.actors.all %}
							<div class="item">
								<div class="w3l-movie-gride-agile w3l-movie-gride-agile1">
									<a href="" class="hvr-shutter-out-horizontal"><img src="{{actor.image.url}}" title="album-name" class="img-responsive" alt=" ">
									</a>
									<div class="mid-1 agileits_w3layouts_mid_1_home">
										<div class="w3l-movie-text">
											<h6><a href="">{{actor.name}}</a></h6>
										</div>
									</div>
								</div>
								</div>
								{% endfor %}
								</div>

					</div> -->
					

					<div class="clearfix"> </div>


				</div>
				<div class="col-md-4 single-right">
					<h3>Aktyor haqida</h3>
					<div class="single-grid-right">
						<p>Ismi: {{actor.name}}</p>
						{% autoescape off %}
						<p>Karyera: {{actor.karyera}}</p>
						{% endautoescape %}
						<p>Tug'ilgan kuni: {{actor.birth}}</p>
						<p>Millati: {{actor.nation}}</p>
						<p>Tili: {{actor.lang}}</p>
						<p>Ma'lumotlar:
						{% autoescape off %}
						{{actor.desc}}
						{% endautoescape %}</p>
	
					</div>
					<div class="single-grid-right">
						<h4>Boshqa Aktyorlar</h4>
						{% for actor in l_actors %}
						<div class="single-right-grids">
							<div class="col-md-4 single-right-grid-left">
								<a href="{{actor.get_actor}}"><img src="{{actor.image.url}}" alt=""></a>
							</div>
							<div class="col-md-8 single-right-grid-right">

								<a href="{{actor.get_actor}}" class="title">{{actor.title}}</a>
								<p class="author"><a href="{{actor.get_actor}}" class="author">{{actor.name}}</a></p>
								<p class="author"><a href="{{actor.get_actor}}" class="author">{{actor.nation}}</a></p>
								<p class="author"><a href="{{actor.get_actor}}" class="author">{{actor.country}}</a></p>
								<p class="author"><a href="{{actor.get_actor}}" class="author">{{actor.boyi}} sm</a></p>
<!-- 
								{% for actor in movie.actors.all|slice:":2"%}
								<p class="views" >
									{{actor.name}}
								</p>
								{% endfor %} -->


						<!-- 		<p class="views">{{movie.world_premiere}}</p> -->
							</div>
							<div class="clearfix"> </div>
						</div>
						{% endfor %}
					</div>
				</div>



				<div class="clearfix"> </div>
			</div>
				<!-- //movie-browse-agile -->
				<!--body wrapper start-->
			<div class="w3_agile_banner_bottom_grid">
				<div id="owl-demo" class="owl-carousel owl-theme">
					{% for actor_m in movie.actor.movie %}
					<p>{{ actor_m.title }}</p>
					{% endfor %}
					<div class="item">
						<div class="w3l-movie-gride-agile w3l-movie-gride-agile1">
							<a href="single.html" class="hvr-shutter-out-horizontal"><img src="images/m13.jpg" title="album-name" class="img-responsive" alt=" " />
								<div class="w3l-action-icon"><i class="fa fa-play-circle" aria-hidden="true"></i></div>
							</a>
							<div class="mid-1 agileits_w3layouts_mid_1_home">
								<div class="w3l-movie-text">
									<h6><a href="single.html">Citizen Soldier</a></h6>
								</div>
								<div class="mid-2 agile_mid_2_home">
									<p>2016</p>
									<div class="block-stars">
										<ul class="w3l-ratings">
											<li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
											<li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
											<li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
											<li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
											<li><a href="#"><i class="fa fa-star-half-o" aria-hidden="true"></i></a></li>
										</ul>
									</div>
									<div class="clearfix"></div>
								</div>
							</div>
							<div class="ribben">
								<p>NEW</p>
							</div>
						</div>
					</div>

				</div>
			</div>
		<!--body wrapper end-->


				</div>
				<!-- //w3l-latest-movies-grids -->
			</div>
		</div>
	<!-- //w3l-medile-movies-grids -->

{% endblock %}

templates/base.html
{% load crispy_forms_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>One Movies an Entertainment Category Flat Bootstrap Responsive Website Template | Home :: w3layouts</title>
<!-- for-mobile-apps -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="One Movies Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
		function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- //for-mobile-apps -->
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
<link rel="stylesheet" href="{% static 'css/contactstyle.css' %}" type="text/css" media="all" />
<link rel="stylesheet" href="{% static 'css/faqstyle.css' %}" type="text/css" media="all" />
<link href="{% static 'css/single.css' %}" rel='stylesheet' type='text/css' />
<link href="{% static 'css/medile.css' %}" rel='stylesheet' type='text/css' />
<link href="{% static 'css/jquery.slidey.min.css' %}" rel="stylesheet">
<link href="css/popuo-box.css' %}" rel="stylesheet" type="text/css" media="all" />
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
<script type="text/javascript" src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
<link href="{% static 'css/owl.carousel.css' %}" rel="stylesheet" type="text/css" media="all">
<script src="{% static 'js/owl.carousel.js' %}"></script>
<script>
	$(document).ready(function() {
		$("#owl-demo").owlCarousel({

		  autoPlay: 3000, //Set AutoPlay to 3 seconds

		  items : 5,
		  itemsDesktop : [640,4],
		  itemsDesktopSmall : [414,3]

		});

	});
</script>
<!-- //banner-bottom-plugin -->
<link href='//fonts.googleapis.com/css?family=Roboto+Condensed:400,700italic,700,400italic,300italic,300' rel='stylesheet' type='text/css'>
<!-- start-smoth-scrolling -->
<script type="text/javascript" src="{% static 'js/move-top.js' %}"></script>
<script type="text/javascript" src="{% static 'js/easing.js' %}"></script>
<script type="text/javascript">
	jQuery(document).ready(function($) {
		$(".scroll").click(function(event){
			event.preventDefault();
			$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
		});
	});
</script>
<!-- start-smoth-scrolling -->
</head>

<body>
<!-- header -->
	<div class="header">
		<div class="container">
			<div class="w3layouts_logo">
				<a href="index.html"><h1>One<span>Movies</span></h1></a>
			</div>
			<div class="w3_search">
				<form action="{% url 'movie:search_result' %}" method="get" >
					<input type="text" name="q" placeholder="Qidiruv" required="">
					<input type="submit" value="Go">
				</form>
			</div>
			<div class="w3l_sign_in_register">
				<ul>
					<center>
					<li><i class="fa fa-phone" aria-hidden="true"></i> (+998)99-727-56-11</li>
					<br>

						{% if user.is_authenticated %}
						<li><a href="{% url 'account_logout' %}">Chiqish</a></li>
						{% else %}
						<li><a href="{% url 'account_login' %}">Login</a></li>
						{% endif %}
						<center/>
				</ul>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
<!-- //header -->
<!-- bootstrap-pop-up -->
	<div class="modal video-modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModal">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					Sign In & Sign Up
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				</div>
			
			</div>
		</div>
	</div>
	<script>
		$('.toggle').click(function(){
		  // Switches the Icon
		  $(this).children('i').toggleClass('fa-pencil');
		  // Switches the forms
		  $('.form').animate({
			height: "toggle",
			'padding-top': 'toggle',
			'padding-bottom': 'toggle',
			opacity: "toggle"
		  }, "slow");
		});
	</script>
<!-- //bootstrap-pop-up -->
<!-- nav -->
	<div class="movies_nav">
		<div class="container">
			<nav class="navbar navbar-default">
				<div class="navbar-header navbar-left">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
				</div>
				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
					<nav>
						<ul class="nav navbar-nav">
							<li class="active"><a href="{% url 'movie:movies_list' %}">Home</a></li>
							{% for genre in categories %}
							<li><a href="{{genre.get_absolute_url}}">{{genre.name}}</a></li>
							{% endfor %}
							<li><a href="{% url 'movie:news' %}">Yangiliklar</a></li>
							<li><a href="#">Short Codes</a></li>
						</ul>
					</nav>
				</div>
			</nav>
		</div>
	</div>
<!-- //nav -->


		{% block content %}

		{% endblock %}

			<!-- flexSlider -->
				<link rel="stylesheet" href="{% static 'css/flexslider.css' %}" type="text/css" media="screen" property="" />
				<script defer src="{% static 'js/jquery.flexslider.js' %}"></script>
				<script type="text/javascript">
				$(window).load(function(){
				  $('.flexslider').flexslider({
					animation: "slide",
					start: function(slider){
					  $('body').removeClass('loading');
					}
				  });
				});
			  </script>
			<!-- //flexSlider -->

	<!-- pop-up-box -->
		<script src="{% static 'js/jquery.magnific-popup.js' %}" type="text/javascript"></script>
	<!--//pop-up-box -->

	<script>
		$(document).ready(function() {
		$('.w3_play_icon,.w3_play_icon1,.w3_play_icon2').magnificPopup({
			type: 'inline',
			fixedContentPos: false,
			fixedBgPos: true,
			overflowY: 'auto',
			closeBtnInside: true,
			preloader: false,
			midClick: true,
			removalDelay: 300,
			mainClass: 'my-mfp-zoom-in'
		});

		});
	</script>
<!-- //Latest-tv-series -->

<!-- footer -->

</style>
	<div class="footer">
		<div class="container">
			<div class="w3ls_footer_grid">
				<div class="col-md-6 w3ls_footer_grid_left">
					<div class="w3ls_footer_grid_left1">
						<h2>Subscribe to us</h2>
						<div class="w3ls_footer_grid_left1_pos">
							<form action="{% url 'movie:email_sender' %}" method="post">
								{% csrf_token %}
								{{form_base | crispy}}
								<input type="submit" name="" value="Submit">
							</form>
						</div>
					</div>
				</div>
				<div class="col-md-6 w3ls_footer_grid_right">
					<a href="index.html"><h2>One<span>Movies</span></h2></a>
				</div>
				<div class="clearfix"> </div>
			</div>
			<div class="col-md-5 w3ls_footer_grid1_left">
				<p>&copy; 2016 One Movies. All rights reserved | Design by <a href="http://w3layouts.com/">W3layouts</a></p>
			</div>
			<div class="col-md-7 w3ls_footer_grid1_right">
				<ul>
					<li>
						<a href="genres.html">Movies</a>
					</li>
					<li>
						<a href="faq.html">FAQ</a>
					</li>
					<li>
						<a href="horror.html">Action</a>
					</li>
					<li>
						<a href="genres.html">Adventure</a>
					</li>
					<li>
						<a href="comedy.html">Comedy</a>
					</li>
					<li>
						<a href="icons.html">Icons</a>
					</li>
					<li>
						<a href="contact.html">Contact Us</a>
					</li>
				</ul>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
<!-- //footer -->
<!-- Bootstrap Core JavaScript -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script>
$(document).ready(function(){
    $(".dropdown").hover(
        function() {
            $('.dropdown-menu', this).stop( true, true ).slideDown("fast");
            $(this).toggleClass('open');
        },
        function() {
            $('.dropdown-menu', this).stop( true, true ).slideUp("fast");
            $(this).toggleClass('open');
        }
    );
});
</script>
<!-- //Bootstrap Core JavaScript -->
<!-- here stars scrolling icon -->
	<script type="text/javascript">
		$(document).ready(function() {
			/*
				var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear'
				};
			*/

			$().UItoTop({ easingType: 'easeOutQuart' });

			});
	</script>
<!-- //here ends scrolling icon -->
</body>
</html>

templates/categories_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="general_social_icons">
	<nav class="social">
		<ul>
			<li class="w3_twitter"><a href="#">Twitter <i class="fa fa-twitter"></i></a></li>
			<li class="w3_facebook"><a href="#">Facebook <i class="fa fa-facebook"></i></a></li>
			<li class="w3_dribbble"><a href="#">Dribbble <i class="fa fa-dribbble"></i></a></li>
			<li class="w3_g_plus"><a href="#">Google+ <i class="fa fa-google-plus"></i></a></li>
		</ul>
  </nav>
</div>
<!-- faq-banner -->
	<div class="faq">
		<h4 class="latest-text w3_faq_latest_text w3_latest_text">Movies List</h4>
			<div class="container">
				<div class="agileits-news-top">
					<ol class="breadcrumb">
					  <li><a href="{% url 'movie:movies_list' %}">Bosh menyu</a></li>
					  <li class="active">O'zbek kinolar</li>
					</ol>

				</div>
				<div>

					{% for movie in page_obj %}
					<div class="col-md-2 w3l-movie-gride-agile">
								<a href="{{movie.get_movie}}" class="hvr-shutter-out-horizontal"><img src="{{movie.poster.url}}" title="album-name" class="img-responsive" alt=" " />
									<div class="w3l-action-icon"><i class="fa fa-play-circle" aria-hidden="true"></i></div>
								</a>
								<div class="mid-1 agileits_w3layouts_mid_1_home">
									<div class="w3l-movie-text">
										<h6><a href="{{movie.get_movie}}">{{movie.title}}</a></h6>
									</div>
									<div class="mid-2 agile_mid_2_home">
										<p>{{movie.year}}</p>
										<div class="block-stars">
											<ul class="w3l-ratings">
												<li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
												<li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
												<li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
												<li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
												<li><a href="#"><i class="fa fa-star-half-o" aria-hidden="true"></i></a></li>
											</ul>
										</div>
										<div class="clearfix"></div>
									</div>
								</div>

							</div>
					{% endfor %}
				</div>


			</div>


	</div>
	{% if page_obj.paginator %}
	<div class="" style="">
		<ul class="pagination">
			{% if page_obj.has_previous %}
				<li class="page-item"><a href="?page=1" class="page-link" >Oldingi</a></li>
<!-- 				<li class="page-item"><a href="?page={{ page_obj.previous_page_number }}"></a></li> -->
			{% else %}
				<li class="disabled"><a href="" class="disabled" >Oldingi</a></li>
			{% endif %}

			{% for page in page_obj.paginator %}
			<li class="page-item"><a class="page-link" href="?page={{page.number}}">{{page.number}}</a></li>
			{% endfor %}

			{% if page_obj.has_next %}
				<li class="page-item"><a href="?page={{ page_obj.next_page_number }}">keyingi</a></li>
<!-- 				<li class="page-item"><a href="?page={{ page_obj.paginator.num_pages }}"></a></li> -->
			{% else %}
				<li class="disabled"><a href="" class="disabled">keyingi</a></li>
			{% endif %}

		</ul>
	</div>
	{% else %}
	<div></div>
	{% endif %}
<!-- //faq-banner -->
{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<!-- contact -->
	<div class="contact-agile">
		<div id="map"></div>
		<div class="faq">
			<h4 class="latest-text w3_latest_text">Contact Us</h4>
			<div class="container">
				<div class="col-md-3 location-agileinfo">
					<div class="icon-w3">
						<span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
					</div>
					<h3>Address</h3>
					<h4>345 Setwant natrer,</h4>
					<h4>Washington,</h4>
					<h4>United States.</h4>
				</div>
				<div class="col-md-3 call-agileits">
					<div class="icon-w3">
						<span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>
					</div>
					<h3>Call</h3>
					<h4>+18044126235</h4>
					<h4>+14056489808</h4>
					<h4>+16789339049</h4>
				</div>
				<div class="col-md-3 mail-wthree">
					<div class="icon-w3">
						<span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
					</div>
					<h3>Email</h3>
					<h4><a href="mailto:info@example.com">example1@mail.com</a></h4>
					<h4><a href="mailto:info@example.com">example2@mail.com</a></h4>
					<h4><a href="mailto:info@example.com">example3@mail.com</a></h4>
				</div>
				<div class="col-md-3 social-w3l">
					<div class="icon-w3">
						<span class="glyphicon glyphicon-user" aria-hidden="true"></span>
					</div>
					<h3>Social media</h3>
					<ul>
						<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i><span class="text">Facebook</span></a></li>
						<li class="twt"><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i><span class="text">Twitter</span></a></li>
						<li class="ggp"><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i><span class="text">Google+</span></a></li>
					</ul>
				</div>
				<div class="clearfix"></div>
				<form action="" method="post" id="my-form">
					{% csrf_token %}
					{{default_form |crispy}}
					<input type="submit" value="SEND MESSAGE">
				</form>
			</div>
		</div>
	</div>

	<script>
		function FormReset(form) {
			let form = document.querySelector('#my-form');
			form.clear();
			console.log('WORKEEEEEEDDDDD');
		}
		FormReset();
	</script>
{% endblock %}

templates/list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="general_social_icons">
	<nav class="social">
		<ul>
			<li class="w3_twitter"><a href="#">Twitter <i class="fa fa-twitter"></i></a></li>
			<li class="w3_facebook"><a href="#">Facebook <i class="fa fa-facebook"></i></a></li>
			<li class="w3_dribbble"><a href="#">Dribbble <i class="fa fa-dribbble"></i></a></li>
			<li class="w3_g_plus"><a href="#">Google+ <i class="fa fa-google-plus"></i></a></li>				  
		</ul>
  </nav>
</div>
<!-- faq-banner -->
	<div class="faq">
		<h4 class="latest-text w3_faq_latest_text w3_latest_text">Movies List</h4>
			<div class="container">
				<div class="agileits-news-top">
					<ol class="breadcrumb">
					  <li><a href="{% url 'movie:movies_list' %}">Bosh menyu</a></li>
					  <li class="active">Qidiruv Natijalari</li>
					</ol>

				</div>
				<div>
					{% for movie in object_list %}
					<div class="col-md-2 w3l-movie-gride-agile">
								<a href="{{movie.get_movie}}" class="hvr-shutter-out-horizontal"><img src="{{movie.poster.url}}" title="album-name" class="img-responsive" alt=" " />
									<div class="w3l-action-icon"><i class="fa fa-play-circle" aria-hidden="true"></i></div>
								</a>
								<div class="mid-1 agileits_w3layouts_mid_1_home">
									<div class="w3l-movie-text">
										<h6><a href="{{movie.get_movie}}">{{movie.title}}</a></h6>							
									</div>
									<div class="mid-2 agile_mid_2_home">
										<p>{{movie.year}}</p>
										<div class="block-stars">
											<ul class="w3l-ratings">
												<li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
												<li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
												<li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
												<li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
												<li><a href="#"><i class="fa fa-star-half-o" aria-hidden="true"></i></a></li>
											</ul>
										</div>
										<div class="clearfix"></div>
									</div>
								</div>
								<div class="ribben">
									<p>NEW</p>
								</div>
							</div>
					{% endfor %}
				</div>
				

			</div>
	</div>
<!-- //faq-banner -->
{% endblock %}